### ISSUE TITLE
Error encountered using client.Insert<T>() - Organization ID: id value of incorrect type

### ISSUE THREAD

**Issue by donners77** [clamidity/SalesforceMagic#16]
Hi Michael,

Thank you for making this amazing library available.  I've installed the nuget package and have had great success with the GetSession(), Count<T>() and Query<T>() methods against my Salesforce sandbox.

I've run into an error though, when I try and insert a new record. Salesforce is complaining about the Organization ID being of the wrong type, although I am inserting an Account record which doesn't seem to have an Organization Id in it.

Could you provide some pointers on how to fix this error?

Here's some screenshots of what I'm seeing and the code I'm using...
## Error message
![errormessage](https://cloud.githubusercontent.com/assets/5105950/6763961/89e109d6-cfea-11e4-84b1-f256d9fc2488.png)

## Code encountering the error
![codeencounteringerror](https://cloud.githubusercontent.com/assets/5105950/6763971/c3be8746-cfea-11e4-96e9-f6383e79fa1f.png)

## Definition of the Account Dto
![definition of dsoaccountsf](https://cloud.githubusercontent.com/assets/5105950/6763976/de6fb31c-cfea-11e4-9253-f19bf2cff9ba.png)

## The following code using the Microsoft types generated from the WSDL works
![codeusingsoapwsdl](https://cloud.githubusercontent.com/assets/5105950/6763982/039000c0-cfeb-11e4-81ab-12043116f950.png)

Kind regards,
Craig.

**Comment by clamidity** [comment]
Thank you for update. I will check in to this ASAP and let you know what I find.

**Comment by donners77** [comment]
Thanks.

**Comment by benbenwilde** [comment]
@donners77 I don't believe that the source of this error is this library. I think its coming from salesforce because the data you send is not 100% correctly correlated to what is already in salesforce. See if this thread helps - https://success.salesforce.com/answers?id=90630000000glwVAAQ

**Comment by clamidity** [comment]
Closing for now
