### ISSUE TITLE
Malformed query

### ISSUE THREAD

**Issue by benbenwilde** [clamidity/SalesforceMagic#17]
`client.AdvancedQuery<Account>(a => !a.IsDeleted, 50);` 
produces a malformed query: `"Account WHERE IsDeleted = True != True LIMIT 50"`

Should just be `"Account WHERE IsDeleted != True LIMIT 50"`

**Update:** `client.AdvancedQuery<Account>(a => a.IsDeleted != true, 50);` produces the same result.

**Comment by clamidity** [comment]
Just pushed an update that might partially fix this. Can you give it a try? If not this is the area I am currently working on.

**Comment by benbenwilde** [comment]
very nice! I added some tests and gave another little update to the SOQL visitor. I'll submit a pull request in case you're interested.

**Comment by clamidity** [comment]
Solved with commit
